{% set version = "0.6.3" %}

package:
  name: jpype1
  version: {{ version }}

source:
  fn: jpype-{{ version }}.tar.gz
  url: https://github.com/originell/jpype/archive/v{{ version }}.tar.gz
  sha256: 5c447f4ac2d97f60ee1753fa59dd32ebdc29e16571db9ce2fb7a67362d459e22

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - jpype

about:
  home: https://github.com/originell/jpype/
  license: Apache
  license_file: LICENSE
  summary: 'A Python to Java bridge.'
  description: 'A Python to Java bridge.'
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
