{% set version = "0.7.1" %}
{% set name = "JPype1" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c16d01cde9c2c955d76d45675e64b06c3255784d49cea4147024e99a01fbbb18

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - jpype

about:
  home: https://github.com/originell/jpype/
  license: Apache
  license_file: LICENSE
  summary: 'A Python to Java bridge.'
  description: 'A Python to Java bridge.'
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
