{% set version = "1.5.2" %}
{% set name = "jpype1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74a42eccf21d30394c1832aec3985a14965fa5320da087b65029d172c0cec43b

build:
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: jpype1
    script: build_jpype1.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - packaging
        - openjdk >=21
    test:
      imports:
        - jpype
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
      requires:
        - pip
  - name: jpype1-test
    script: build_test.sh
    requirements:
      build:
        - ant
      host:
        - python
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage('jpype1', exact=True) }}
    test:
      source_files:
       - test
      imports:
       - jpype
      commands:
        - pip check
        # We don't have java sql drivers required to run test_sql* tests
        - pytest -vv test/jpypetest --checkjni --ignore-glob="test/jpypetest/test_sql*" -k "not testInvalidArgsFalse"
      requires:
        - python
        - pip
        - pytest
        - pyinstaller
        - jedi >=0.18.0

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Python to Java bridge.
  description: |
    JPype is a Python module to provide full access to Java from within Python. It allows Python to 
    make use of Java specific libraries, explore and visualize Java structures, develop and test Java 
    libraries, make use of scientific computing, and much more. By enabling the use of Python for 
    rapid prototyping and Java for strong typed production code, JPype provides a powerful 
    environment for engineering and code development.
  doc_url: https://jpype.readthedocs.io
  dev_url: https://github.com/jpype-project/jpype

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
  skip-lints:
    # readthedocs.io is unreachable from CI and causes a linter error spam in PR
    - invalid_url
