{% set version = "0.6.2" %}

package:
  name: jpype1
  version: {{ version }}

source:
  fn: jpype-{{ version }}.tar.gz
  url: https://github.com/originell/jpype/archive/v{{ version }}.tar.gz
  sha256: 99206412d80b9d5a81a7cc205267ca63554403eb57f13420302e2f39bfad7f25 

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - jpype

about:
  home: https://github.com/originell/jpype/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'A Python to Java bridge.'
  description: 'A Python to Java bridge.'
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
