{% set version = "1.5.2" %}
{% set name = "jpype1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/jpype-project/jpype/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5bb06e49cfa3879bd29e1a4cf2b92b417ff5a5d6f5bca4fb1bc20194db150df
  patches:
    - 0001-change-javac-target.patch
    - 0002-fix-find_libjvm.patch

build:
  number: 0
  skip: True  # [py<38]
  # Missing openjdk for s390x (not supported)
  skip: True  # [s390x]
  # Skipping windows entirely as it's troublesome
  # we need linux builds asap, and windows is just optional
  # I'll try to get windows working while other platforms are in review
  skip: True  # [win]

requirements:
  build:
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - python
  run:
    - python

outputs:
  - name: jpype1
    script: build_jpype1.sh   # [unix]
    script: build_jpype1.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python
        - openjdk >=21
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - packaging
      run_constrained:
        - openjdk >=21
    test:
      files:
        - simple_test.py
        - pickle_test.py
      imports:
        - jpype
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        - python simple_test.py
        - python pickle_test.py
      requires:
        - pip
        - python
        - openjdk >=21

    # We don't have java sql drivers required to run test_sql* tests
    {% set tests_to_ignore = " --ignore-glob=\"test/jpypetest/test_sql*\"" %}
    # Unstable on osx-64
    {% set tests_to_ignore = tests_to_ignore + " --ignore=test/jpypetest/test_leak.py" %}  # [osx-64]

  - name: jpype1-test
    build:
      # ant not available for osx-arm64
      skip: True  # [arm64]
    script: build_test.sh   # [unix]
    script: build_test.bat  # [win]
    requirements:
      build:
        - ant
      host:
        - python
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage('jpype1', exact=True) }}
    test:
      source_files:
       - test
      imports:
       - jpype
      commands:
        - pip check
        - pytest -vv test/jpypetest --checkjni {{ tests_to_ignore }} -k "not (testInvalidArgsFalse)"
      requires:
        - python
        - pip
        - pytest
        - pyinstaller
        - jedi >=0.18.0
        - openjdk

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Python to Java bridge.
  description: |
    JPype is a Python module to provide full access to Java from within Python. It allows Python to 
    make use of Java specific libraries, explore and visualize Java structures, develop and test Java 
    libraries, make use of scientific computing, and much more. By enabling the use of Python for 
    rapid prototyping and Java for strong typed production code, JPype provides a powerful 
    environment for engineering and code development.
  doc_url: https://jpype.readthedocs.io
  dev_url: https://github.com/jpype-project/jpype

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
  skip-lints:
    # readthedocs.io is unreachable from CI and causes a linter error spam in PR
    - invalid_url
