{% set version = "1.4.1" %}
{% set name = "JPype1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc8ee854073474ad79ae168d90c2f6893854f58936cfa18f3587cadae0d3696d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation.
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
  host:
    - python
    - pip
    - setuptools
    - wheel
    # - setupext unavailable
  run:
    - python
    - typing_extensions  # [py<38]
    - packaging

test:
  imports:
    - jpype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Python to Java bridge.
  description: |
    JPype is a Python module to provide full access to Java from within Python. It allows Python to 
    make use of Java specific libraries, explore and visualize Java structures, develop and test Java 
    libraries, make use of scientific computing, and much more. By enabling the use of Python for 
    rapid prototyping and Java for strong typed production code, JPype provides a powerful 
    environment for engineering and code development.
  doc_url: https://jpype.readthedocs.io
  dev_url: https://github.com/jpype-project/jpype

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
