{% set version = "1.4.1" %}
{% set name = "JPype1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc8ee854073474ad79ae168d90c2f6893854f58936cfa18f3587cadae0d3696d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
  host:
    - python
    - pip
    - setuptools
    - wheel
    # - setupext unavailable
  run:
    - python
    - typing_extensions  # [py<38]
    - packaging

test:
  imports:
    - jpype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python to Java bridge.
  description: A Python to Java bridge.
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
    - Thrameos
