{% set version = "1.0.1" %}
{% set name = "JPype1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f85712734b894145ee82bfa11573a2a50a37ea16cae5bd4dee868114bf2b7828 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - typing_extensions  # [py<3.8]

test:
  imports:
    - jpype

about:
  home: https://github.com/jpype-project/jpype
  license: Apache-2.0
  license_file: LICENSE
  summary: A Python to Java bridge.
  description: A Python to Java bridge.
  doc_url: http://jpype.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - caspervdw
    - marscher
    - mariusvniekerk
