travis:
  secure:
    BINSTAR_TOKEN: uCwKBz+M+YbAa0ZPS3TPGHkrYBmMUB6bU6uWQ237pdx4A7jp4D1azGxrVU8zmpEXpIldvzUIU/7Qs3jIMJ7ScBEsfJbj3iIvLj3P90qch03mU9ArCVbHYHx4xGWKIiIghlYu1NTvMdWlDCwDHRwTpaKYi+vd6ReVnkFZ4V4BIgVunyThP6bZnRQXiyGEaNPXmHO5TkVDxm4wmz2JL8+cM+ZjHURvYkzptZ4g0OAUl1m2+4ISTQJRfBuLnecyEyED/SEa1NR4XbRBPyF71fb03PlVcKmjstRTpn2OyXrQIyvwRqqzAeYs+pik+s5fT04Io8et6CnSRB6rCEdFUMv3Y0AkBIDpBOq5czryZLNxhp8GXfvuABl9ptIBs7TcgZIt3fikl4yEawOTs8PjGF5fwhZxta6DrUioxmC1+vJ48ROHK54ICBD8gcs4nK07k2/b0hc8AsiUuFVAYMgG7FLzkY7Efr+3VixkPyJMhMXANyuySA765QyyLj9nOaciWPWX3v8Mw2VJjCH0ZB4POy7Y6LJrbt6nhWL2c0J8LVR2y1bT8Q+MIjySNEZzjPnk/Kuj1RF9HBQINpH2/3sAI+Kr+ObSNYGK6vC1AyBAm6g6LQ8eIQzfXn2KLTtpKqCquC3qaCLj7fQCHUF4+lHvYwvpD6vPQv2Cue6zazhk1rdbL8U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
