travis:
  secure:
    BINSTAR_TOKEN: a7c8ALW2kc03DCBxUHeSXqTxtL0w7WYvk8tu36F8VMig+9g3h00jv3ECPaSSVQmJZiFFnMNVnUo6Er01nqKxI+yzKbvX36oMMiOuw3vzomknQ0qk/oBAwciBLRq0nGvlp6BuQNUBujcsr+rerrfdxKOri6GhmrLM+DX1HeIdEUkBml+Ixw+mTs7E5xOzgP0KRkVOPNRirCYfg7+TOG0AB1IR5aFUJrVAdm2GjYZ5z7nVpMm9+WZz5GQ+CFIzpN4aspTI//mMDd50NOgrBkaIoosJY8ZDW7kOQiW/OxkwcPNQ0P8J0S92OB1iAheLpzOhTt/BI1qSIVjeCnVtbwt7DBCh6ytFMtFTnUZSbSiRRI7kc/D48UGizeMoeSVsV4BSOQuEwXbmBX2Sjt2JJZrwW3/pwuWe5k8D129LrxbnolBJV/wghhtW7OvYrn104uIqsBrGbeuy6zS4KEg6ntrQLHwhDZXa4JwIMIkGCp6CSI8GIPKaINb7VLqcTHcGo0O9WXNb99x1wnWrIHC0P83xHARcJlgTSu0AyYu40CEWWLRkeXHlmo8bhy4pkYe4vY2mq83n/ER1ADaSwZ763q9CB47FrL6R3Evwv+vxq36kIdaKrZwLYRUdurLb4aYEoRgmSHDrKq5wN0l1HOz8x072ujuNe4Fny45OIaUazake55k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
